[package]
name = "clue-device"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.159"
vlc-rs = "0.3.0"
tiny_http = "0.12.0"
tera = "1.18.1"
multiparty = { version = "0.1", features = ["server", "futures03"] }
log4rs = "1.2.0"


