[package]
name = "clue-device"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.159"
vlc-rs = "0.3.0"
tiny_http = "0.6.0"
tera = "1.18.1"
log4rs = "1.2.0"

[dependencies.multipart]
path = "./multipart"
version = "0.18.0"
feature = ["tiny_http"]
