appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%dT%H:%M:%S%.3f%z)} {device_id} [{h({l})}]: {m}{n}"

  rolling_file:
    kind: rolling_file
    path: "logs/app.{device_id}.log"
    encoder:
      pattern: "{d(%Y-%m-%dT%H:%M:%S%.3f%z)} {device_id} [{h({l})}]: {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: "10MB"
      roller:
        kind: fixed_window
        base: 0
        count: 10
        pattern: "logs/app.{device_id}.{}.log"

  logstash:
    kind: logstash
    hostname: 198.28.182.104
    port: 5044
    buffer_size: 100
    log_queue_len: 1000
    buffer_lifetime: 1s

root:
  level: info
  appenders:
    - stdout
    - rolling_file
    - logstash
