appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {h({l})} {m}{n}"

  rolling_file:
    kind: rolling_file
    path: "logs/app.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {h({l})} {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: "10MB"
      roller:
        kind: fixed_window
        base: 0
        count: 10
        pattern: "logs/app.{d(%Y-%m-%d_%H-%M-%S)}.{}.log"

  graylog:
    additional_fields:
      component: rust-cs
    buffer_duration: 5
    buffer_size: 5
    hostname: 10.0.0.150
    kind: buffer
    level: Informational
    null_character: true
    port: 12201
    use_tls: false

root:
  level: info
  appenders:
    - stdout
    - rolling_file
    - graylog